name: Webserv Make & Run Test

on:
  push:
    branches: [main]

jobs:
  ex00:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1.4.1
      - name: compile(windows)
        run: |
          cl hello.c
        if: matrix.os == 'windows-latest'
      - name: compile(ubuntu)
        run: |
          gcc hello.c
        if: matrix.os == 'ubuntu-latest'
      - name: compile(macos)
        run: |
          clang hello.c
        if: matrix.os == 'macos-latest'
      - name: run(windows)
        run: |
          hello.exe
        shell: cmd
        if: matrix.os == 'windows-latest'
      - name: run(ubuntu)
        run: |
          ./a.out
        if: matrix.os == 'ubuntu-latest'
      - name: run(macos)
        run: |
          ./a.out
        if: matrix.os == 'macos-latest'

